apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus
    app.kubernetes.io/part-of: tekton-tutorial
  name: java-quarkus
  namespace: mshaposh
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: java-quarkus
status:
  loadBalancer: {}
